services:
  phalcon5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8076:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - odoo
    environment:
      DB_HOST: mysql
      DB_NAME: phalcon_db
      DB_USERNAME: root
      DB_PASSWORD: secret
      ODOO_URL: "http://odoo:8069"
      ODOO_DB: "new-odoo"
      ODOO_USERNAME: "admin@gmail.com"
      ODOO_PASSWORD: "admin"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: phalcon_db
    ports:
      - "8306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:

      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8307:80"
    depends_on: 


      - mysql
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=odoo19
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - coba_postgres_data:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    restart: unless-stopped

  odoo:
    image: odoo:19
    depends_on:
      - postgres
    ports:
      - "8070:8069"
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
      - DB=new-odoo
      - ODOO_DEMO=False
    volumes:
      - coba_odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  mysql_data:
  coba_postgres_data:
  coba_odoo_data: